version: '3.8'

services:
  api-dev:
    build:
      context: .
      target: dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3333:3333"
  api-prod:
    build:
      context: .
      target: production
    ports:
      - "3334:3333"