name: Run E2E Tests

on: [pull_request]

jobs: 
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    steps:
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      
      - uses: actions/checkout@v3
      - run: pnpm i

      - run: npm run test:e2e
        env:
          GITHUB_API_URL: ${{ vars.API_URL }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}